"""
Anamnesis type definitions.

This module exports all type definitions for the Anamnesis semantic code analysis system.
"""

# Core types
from .core import (
    AnalyzedConcept,
    AstNode,
    CodebaseAnalysisResult,
    ComplexityMetrics,
    ConceptEvolution,
    ConceptRelationship,
    ConceptSummary,
    LearnedConcept,
    LearnedPattern,
    LineRange,
    ParseResult,
    RelationshipType,
    SemanticConcept,
    SemanticConceptType,
    Symbol,
    TechnicalDebtLevel,
)

# Error types
from .errors import (
    AnamnesisError,
    ConfigurationError,
    DatabaseError,
    ErrorCode,
    ErrorFactory,
    ExecutionError,
    LearningError,
    MCPErrorCode,
    MCPErrorUtils,
    ResourceError,
    AnamnesisSystemError,
    ValidationError,
)

# Pattern types
from .patterns import (
    AnalyzedPattern,
    DeveloperPattern,
    PatternConstraint,
    PatternContent,
    PatternExample,
    PatternSummary,
    PatternType,
    PatternVariable,
    RelevantPattern,
)

# Analysis types
from .analysis import (
    AIInsight,
    CodebaseAnalysis,
    DirectoryStructure,
    EntryPoint,
    FeatureMap,
    FeatureMapResult,
    FileIntelligence,
    FileMetadata,
    KeyDirectory,
    ProjectDecision,
    WorkSession,
)

# MCP response types
from .mcp_responses import (
    AnalysisSummary,
    AnalyzeCodebaseResponse,
    AutoLearnResponse,
    CodingApproach,
    CodingApproachResponse,
    CodingStyle,
    ComponentStatus,
    ContributeInsightsResponse,
    CurrentWork,
    DeveloperProfile,
    DeveloperProfileResponse,
    HealthCheck,
    HealthCheckResponse,
    IntelligenceMetrics,
    IntelligenceMetricsResponse,
    LearnCodebaseResponse,
    LearningStatus,
    MCPResponse,
    PatternRecommendation,
    PatternRecommendationsResponse,
    PerformanceMetrics,
    PerformanceStatusResponse,
    PreferredPattern,
    ProjectBlueprintResponse,
    SearchCodebaseResponse,
    SearchResult,
    SemanticInsight,
    SemanticInsightsResponse,
    SystemStatusResponse,
)

__all__ = [
    # Core types
    "LineRange",
    "SemanticConceptType",
    "RelationshipType",
    "TechnicalDebtLevel",
    "ConceptRelationship",
    "ConceptEvolution",
    "SemanticConcept",
    "ConceptSummary",
    "AnalyzedConcept",
    "ComplexityMetrics",
    "AstNode",
    "Symbol",
    "ParseResult",
    "CodebaseAnalysisResult",
    "LearnedConcept",
    "LearnedPattern",
    # Error types
    "MCPErrorCode",
    "ErrorCode",
    "AnamnesisError",
    "ValidationError",
    "ResourceError",
    "LearningError",
    "ExecutionError",
    "ConfigurationError",
    "AnamnesisSystemError",
    "DatabaseError",
    "ErrorFactory",
    "MCPErrorUtils",
    # Pattern types
    "PatternType",
    "PatternVariable",
    "PatternConstraint",
    "PatternContent",
    "PatternExample",
    "DeveloperPattern",
    "PatternSummary",
    "AnalyzedPattern",
    "RelevantPattern",
    # Analysis types
    "FileMetadata",
    "DirectoryStructure",
    "CodebaseAnalysis",
    "FileIntelligence",
    "AIInsight",
    "FeatureMap",
    "EntryPoint",
    "KeyDirectory",
    "WorkSession",
    "ProjectDecision",
    "FeatureMapResult",
    # MCP response types
    "LearningStatus",
    "AnalysisSummary",
    "AnalyzeCodebaseResponse",
    "SearchResult",
    "SearchCodebaseResponse",
    "ProjectBlueprintResponse",
    "LearnCodebaseResponse",
    "SemanticInsight",
    "SemanticInsightsResponse",
    "PatternRecommendation",
    "PatternRecommendationsResponse",
    "CodingApproach",
    "CodingApproachResponse",
    "PreferredPattern",
    "CodingStyle",
    "CurrentWork",
    "DeveloperProfile",
    "DeveloperProfileResponse",
    "ContributeInsightsResponse",
    "AutoLearnResponse",
    "ComponentStatus",
    "SystemStatusResponse",
    "IntelligenceMetrics",
    "IntelligenceMetricsResponse",
    "PerformanceMetrics",
    "PerformanceStatusResponse",
    "HealthCheck",
    "HealthCheckResponse",
    "MCPResponse",
]
